name: Cargo Build & Test

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest Windows and Ubuntu
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]
        toolchain:
          - stable
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo fmt --all -- --check  
      - run: cargo clippy --verbose
      - run: cargo test --verbose

  build_and_test:
    name: Rust project - latest macOS
    strategy:
      matrix:
        platform: [macos-latest]
        toolchain:
          - stable
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo fmt --all -- --check  
      - run: cargo clippy --verbose
      - run: cargo test --verbose